### ISSUE TITLE
How to compile it using ionic cli ?

### ISSUE THREAD

**Issue by guypld** [ionic-team/ionic-react-conference-app#9]
Hi,

Nice project! 
Compiled successfully with npm, but I was wondering if it can be compiled with ionic cli (build for android/ios).
(I will play with it a little bit and will update).

Thanks.

**Comment by jthoms1** [comment]
Currently we do not have support for the CLI in react.  This will most likely be added soon with support through Capacitor.  More details can be found here: https://github.com/ionic-team/ionic/tree/master/react#publishing-a-native-application

**Comment by anatoliyarkhipov** [comment]
Hi, Josh! Thank you for working on such awesome project!

Can I ask you to elaborate a little bit on how do we run the app on Android? I tried to follow the commands from the link you provided above, but since I'm completely new to Ionic App they don't make much sense. Like, for example, when I tried to run `ionic capacitor add`, it asked me for an `ionic.config.json`. Okay, then, I added the config via `ionic init`, but now it needs me to implement NPM script `ionic:serve`, because I chose `custom` type. And so on.

I'm still trying to investigate the docs, but it would be really helpful if you can provide a minimal set of commands to serve the app on a mobile device.

**Comment by avalanche1** [comment]
One year+ later - still dont see in the docs how to build a native app from this demo.
Is this poosible now?
